kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  labels:
    app: demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: demo-app
        image: ingenhaag/demo-app:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/opt/data"
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: demo-app-pvc
