apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-app-statefulset
spec:
  selector:
    matchLabels:
      app: demo-app-statefulset
  serviceName: "nginx-statefulset"
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app-statefulset
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: demo-app-statefulset
        image: ingenhaag/demo-app:latest
        ports:
        - containerPort: 8080
          name: web
        volumeMounts:
        - name: data
          mountPath: /opt/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-statefulset
  labels:
    app: demo-app-statefulset
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  clusterIP: None
  selector:
    app: demo-app-statefulset