apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-files
data:
  game.properties: |-
    enemies=aliens
    lives=3
    enemies.cheat=true
  ui.properties: |-
    color.good=purple
    color.bad=yellow
    allow.textmode=true