kind: Service
apiVersion: v1
metadata:
  name: demo-app-service-clusterip
spec:
  type: ClusterIP
  selector:
    app: demo-app
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080